export const citations = [
    "La cuisine est un art. L'art de manger des chips devant la télévision.",
    "Je ne suis pas un chef étoilé, mais je suis capable de brûler de l'eau.",
    "La cuisine, c'est le seul endroit où tu peux jouer avec ton nourriture sans te faire gronder.",
    "La vie est trop courte pour boire du mauvais vin et manger de la mauvaise pizza.",
    "La cuisine est un langage universel. Sauf si tu es un mauvais cuisinier, alors personne ne te comprend.",
    "Mon four a décidé de jouer à 'Cuit ou Carbonisé'. C'est une surprise à chaque fois.",
    "La cuisine est simple. Il suffit de couper, mélanger et prier pour que ça ait bon goût.",
    "La meilleure façon de tuer un gâteau au chocolat, c'est de l'avaler entier.",
    "La cuisine, c'est comme la vie : parfois ça brûle, parfois ça déborde, mais au final, c'est toujours délicieux.",
    "Ma cuisine est si petite que les souris se font un câlin quand je fais la vaisselle.",
    "J'ai fait un gâteau hier. Les pompiers sont venus éteindre les bougies.",
    "Si la cuisine était une science exacte, les chefs ne porteraient pas de toques, mais des blouses blanches.",
    "La cuisine, c'est comme un concert : des ingrédients qui jouent en harmonie pour créer un chef-d'œuvre.",
    "La cuisine est l'art de transformer les légumes en un plat que les enfants refuseront de manger.",
    "Les régimes alimentaires sont comme les relations amoureuses : ils commencent avec de bonnes intentions, puis on finit par manger une boîte de cookies entière.",
    "Mon objectif dans la vie ? Être assez bon en cuisine pour que mes enfants ne demandent pas à manger chez leurs amis.",
    "La cuisine est une science complexe. Parfois, j'ajoute du sel et ça devient encore plus fade.",
    "Si la cuisine était facile, tout le monde serait un chef. Mais apparemment, tout le monde est déjà un critique gastronomique.",
    "Mon régime alimentaire est simple : si ça a bon goût, j'en veux plus. Si ça n'a pas bon goût, j'en veux quand même plus.",
    "Mon four a deux modes : 'trop chaud' et 'pas assez chaud'. Il ne connaît pas le juste milieu.",
    "Les recettes sont comme les ex : elles promettent beaucoup, mais au final, tu te retrouves avec un plat insipide.",
    "J'ai essayé d'être végétarien, mais mon corps est un faible. Il a besoin de bacon.",
    "La cuisine est une aventure culinaire. Parfois, tu te perds, et parfois, tu te retrouves avec des épices dans les yeux.",
    "Les échecs en cuisine sont des succès en attente de ketchup.",
    "La cuisine, c'est l'art de transformer des ingrédients en plats instagrammables.",
    "Les frites sont mes légumes préférés. Oui, je suis une personne très saine.",
    "La cuisine, c'est comme la musique : parfois ça sonne faux, mais ça peut quand même être délicieux.",
    "J'ai une relation amour-haine avec la cuisine. Je l'aime quand ça marche, je la déteste quand ça brûle.",
    "Mon plat signature ? Les réservations au restaurant.",
    "La cuisine est un mystère. Comment les chefs font-ils pour avoir autant d'ustensiles propres et moi autant de vaisselle sale ?",
    "La cuisine est l'art de transformer les ingrédients en une montagne de vaisselle sale.",
    "La cuisine, c'est comme la mode : parfois tu es à la pointe de la tendance, et parfois tu portes un tablier taché de sauce tomate.",
    "Les meilleures recettes sont celles qui commencent par 'Ouvrir un paquet de chips'.",
    "La cuisine, c'est l'art de transformer des aliments en restes à emporter.",
    "La cuisine est un marathon. Sauf que dans mon cas, je triche et je commande une pizza à mi-chemin.",
    "Le secret d'une bonne cuisine ? Ne jamais laisser les enfants participer.",
    "J'ai essayé de suivre une recette saine une fois. Maintenant, je suis en rééducation pour ma dépendance au chocolat.",
    "Mon niveau de compétence en cuisine est inversement proportionnel à mon amour pour la nourriture.",
    "La cuisine, c'est l'art de transformer des aliments frais en montagnes de vaisselle sale.",
    "La cuisine, c'est comme un spectacle : les légumes sont les acteurs de soutien, mais le dessert est la star du show.",
    "La cuisine est un mélange d'art et de science, avec une bonne dose de désordre créatif.",
    "Je ne crois pas aux régimes. Je préfère croire en un bon équilibre entre le chocolat et les légumes.",
    "La cuisine, c'est comme une symphonie : chaque ingrédient est une note, et le plat final est une mélodie délicieuse.",
    "La cuisine est mon terrain de jeu. Les casseroles sont mes jouets et les épices sont mes couleurs.",
    "La cuisine est comme l'amour : il faut parfois suivre une recette, mais parfois il suffit de se laisser guider par son instinct.",
    "La cuisine est un moyen de célébrer la vie. Et aussi de célébrer le fait que quelqu'un d'autre fera la vaisselle.",
    "Les recettes sont comme les règles : elles sont faites pour être brisées, surtout quand il s'agit de desserts.",
    "La cuisine, c'est comme un jeu de piste. Parfois, tu finis par trouver un délicieux plat, parfois tu finis par commander une pizza.",
    "La cuisine est un moyen de montrer à quelqu'un que tu l'aimes. Surtout si tu as raté toutes les autres formes d'expression.",
    "La cuisine est une aventure culinaire. Parfois, tu découvres de nouvelles saveurs, parfois tu découvres de nouvelles façons de brûler des toasts.",
    "La cuisine, c'est comme la mode : certaines tendances sont éphémères, mais le fromage est toujours à la mode.",
    "La cuisine, c'est l'art de faire de petites choses pour impressionner tes invités et de grands désordres pour les divertir.",
    "La cuisine est une expérience sensorielle. Sauf si tu brûles la nourriture, alors c'est juste une expérience olfactive.",
    "La cuisine est un langage d'amour. Un bon plat peut faire fondre même le cœur le plus froid.",
    "La cuisine est comme une partie de cache-cache avec les épices. Parfois, tu les trouves tous, et parfois, tu trouves du paprika six mois plus tard.",
    "La cuisine est une expérience sociale. Rien ne rassemble les gens comme un bon repas et un peu de vin.",
    "La cuisine est un moyen de montrer ton amour sans dire un mot. Sauf si tu cries 'C'est prêt !'",
    "La cuisine est un acte de générosité. J'offre toujours mes restes à mon réfrigérateur.",
    "La cuisine est un moyen de mettre de la couleur dans ta vie. Surtout si tu aimes cuisiner avec des légumes arc-en-ciel.",
    "La cuisine, c'est comme la comédie : c'est tout dans le timing. Un gâteau au chocolat mal cuit, c'est une tragédie comique.",
    "La cuisine est un voyage gustatif. Parfois, tu te retrouves dans un petit restaurant familial, parfois, tu te retrouves dans un fast-food à emporter."
  ];
  
 